name: Build grblHAL

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ARM GCC
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10.3-2021.10'

      - name: Build firmware
        run: |
          make
- name: Upload firmware
  uses: actions/upload-artifact@v4
  with:
    name: firmware
    path: build/*.bin
